### ISSUE TITLE
Need LDAP authentication support

### ISSUE THREAD

**Issue by synnack** [frab/frab#17]
Hi, we're currently looking to use frab for OHM (Hack-Tic event in 2013 in the Netherlands in the line of HIP, HAL, WTH and HAR)..

But we need to integrate the authentication with LDAP, as the rest of our infrastructure does. Is this possible?

**Comment by hackman** [comment]
Hmm we still need LDAP authentication support for SHA2017 the next incarnation of OHM2013.

**Comment by BurtGummer** [comment]
is there LDAP authentication support in frab now?

**Comment by manno** [comment]
No, there isn't. I'm currently working on an upgrade to rails 5 and will bring devise back. Devise can be extended to use LDAP I think.

**Comment by zonque** [comment]
Using devise is certainly a good idea, and most of the data model should still fit I guess. I wanted to do the transition some time ago, but then realized that frab was originally based on devised, but then ditched it. Could you explain what was the reason for that?

**Comment by oneiros** [comment]
> is there LDAP authentication support in frab now?

As I mentioned above, authenticating against existing users in an LDAP directory is quite trivial. But this is only part of the solution. There is also the question, if all users in LDAP should be able to log into frab and what role they should assume. Of course you could also create user accounts in frab first and only use LDAP as an alternative authentication mechanism for these users.

But the biggest hurdle imho is new users. frab allows for new users to sign up. So in an LDAP scenario you would need either one of two things:

1.) frab would need additional code to create new user records in LDAP. This is _not_ trivial, especially since every LDAP directory is different. Consequently the LDAP integrations for devise I have seen do not offer this.

2.) As an alternative, frab could provide an option to disable new signups.  But this would of course render some of frab's best features useless.

> I wanted to do the transition some time ago, but then realized that frab was originally based on devised, but then ditched it. Could you explain what was the reason for that?

This is ancient history, but for the record:

frab has a use-case that devise did not support very well back in the day: frab has different interfaces that are seperated from one another, the admin interface for organizers and the call for papers interface for submitters. Submitters should of course only see the latter, but organizers sometimes need to submit proposals, so they need be able to access both interfaces.

I do not recall the specific problems I had, but I do remember very well, that I had to wrestle with devise on more than one occassion and still failed to make it work the way I wanted it to. I spent hours in the debugger, stepping through code trying to understand the flow. devise is based on warden, a rack middleware, and simply trying to find out what way a username and password take through the code during login made my head hurt.

I had similar problems with devise in other projects since, and stopped using it altogether. Personally I believe that devise is a great project and can be immensely useful, especially if you need all, or most of the features it provides. But it is also surprisingly complex and if all you need is a simple authentication solution and/or you want to do some customization beyond replacing the standard views, this complexity comes back to haunt you.

By the way, I also pondered security implications back then. I used to recommend devise, because it has a lot of users and for something that is vital to the security of your application you want code that has a lot of eyeballs on it. Rolling your own authentication/crypto/etc. is rarely a good idea. What led me to do it anyway was the realization that I simply did not fully understand devise. With my own naive implementation, I can at least reason about the code effectively. I can fix bugs myself. I can decide if a new vulnerability found in Rails affects me or not. With devise I could do none of those things.

Anyway: A lot of time has passed and both devise and frab have changed since I made that decision. So whatever trouble I may have had 6 years ago might not affect frab at all today. Also @manno will have his own experience with devise and it is quite probable he might know better how to handle it than I ever did :smile:

**Comment by manno** [comment]
Well, I've worked with devise a lot, even maintained some [extensions](https://github.com/phatworx/devise_security_extension/issues?utf8=%E2%9C%93&q=mentions%3Amanno%20). Devise is huge and complicated.
I brought it back anyways, since I think it got a lot more readable nowadays. Being able to configure and extend authentication was the main driver behind that change. However that could only happen in the context of new 'main' page feature and  the clean up of the layouts for the different areas of frab.

I learned that devise does not help as much as I hoped, i.e. activating `confirmable` would break the way we edit users as admins.
Like @oneiros explained, adding a devise LDAP extension is probably impossible without a skilled Rails developer.

There are a lot of open questions which depend on the need of the conference. Honestly I don't see LDAP becoming part of frab by default.

Well, at least it got easier after the recent changes. If anybody tries, I'd be interested to know how :)
