### ISSUE TITLE
Non-public rooms in schedule

### ISSUE THREAD

**Issue by manno** [frab/frab#177]
Not all output formats honor the rooms public flag. See JSON and XML for a working scope.

**Comment by ofeldt** [comment]
Is this still a thing? Could you elaborate on what exactly is the required behaviour?

I set up a conf, added 2 events (both public) added them to two rooms. One hidden one public. the exports i checked (JSON, XML, XCal) all honoured the hidden flag, by not displaying rooms in the schedule if hidden, but displaying public events in them (which in turn refer to the rooms by name).

Is the desired behaviour to export events iff this statement holds: event.public? && event.room.public?

**Comment by manno** [comment]
Yes, to export an event it should be both, public and in a public room. Also it should be scheduled and confirmed.

**Comment by ofeldt** [comment]
From my point of view, i don't get why one wants to hide events or rooms at all at this point.

Since we don't have proper types of participants (#161) on a conference, i can't imagine how one should get hold of such an elusive event in the first place.

**If** we add the option of actually managing more than the Tracks of public events later on, this might be a thing. e.g. Adding angel meetings as a track and have it available to participants who are also helpers or something. Not saying we should do this, but this is one of the use cases which comes to mind.

**Comment by manno** [comment]
Both fields were inherited from pentabarfs data model. The idea behind private events, was to have some super-secret, sensitive, submission. You can schedule it so the crew knows the slot is taken, but publish the schedule to the public without the event. Then shortly before the conference starts, set the event to public.

At some point frab started to make public: false the default.
