### ISSUE TITLE
Contradiction in Ruby requirements.

### ISSUE THREAD

**Issue by alvarezp** [frab/frab#184]
Byebug requires Ruby >= 2.0.0.

Debain Wheezy 7 offers Ruby 1.9.3.

Frab states that the required Ruby version is 1.9.3.

```
Installing byebug (2.7.0) 
Gem::InstallError: byebug requires Ruby version >= 2.0.0.
An error occured while installing byebug (2.7.0), and Bundler cannot continue.
Make sure that `gem install byebug -v '2.7.0'` succeeds before bundling.
```

Is byebug necessary? Can it be removed from the Gemfile? Is frab a Ruby 1.9.3 or a Ruby 2.0 app?

**Comment by alvarezp** [comment]
Also, there are many instances of code of syntax `%i(foo bar)` which throws a SyntaxError exception. Apparently the README is outdated and frab is no longer a Ruby 1.9.x application.

**Comment by manno** [comment]
Hi,
Thanks for noticing. I'll update the README, too match the current travis configuration (2.1, 2.2).
 
Installing frab on Debian Wheezy has been difficult for years. Even if you're using rvm/rbenv instead of Wheezies system ruby, you're likely to run into trouble. Dependencies like imagemagick might be too old.

You could try to install a production system without test and development gems:
    bundle install --without="test development"

**Comment by sebix** [comment]
I have the same problem as @alvarezp when trying to install frab in Ubuntu 14.04. I assumed that it was just a lack of ruby-knowledge on my side.

It would be great if the installation instructions would be updated!

**Comment by manno** [comment]
@sebix you could use http://rbenv.org/ or https://rvm.io/ to get an up to date Ruby. Personally I avoid system Ruby.
