### ISSUE TITLE
Add dynamic category sliders

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#295]
In order to allow speakers to hint potential attendees about their lectures, I would add a dynamic set of keywords per conference that will be presented to submitters as sliders or 1-5 star fields.

This can then be used to indicate required prior knowledge, make belong to one ore multiple tracks more fluid, etc and when exported help apps filter lectures by those fields.

**Comment by sebix** [comment]
Isn't this what has been discussed in #156?

**Comment by wvholst** [comment]
No, what the possibility of keywords means is that you can use tags. What Erdgeist appears to be asking for is an indicater of how "advanced" a lecture will be (for example, novice, apprentice, master), with mutually exclusive values.

**Comment by erdgeist** [comment]
Yes, but not only this. Currently we have speakers not sure which track to add their submission to. If we can add sliders for each track, we can allow speakers to mark those as 3/5 Security 2/5 Hardware 4/5 Engineering 1/5 Science, etc. The frontend can even automatically chose the "official" track by whatever track-keyword has the largest value/most stars set.

In the end I imagine apps or the halfnarp suggesting lectures using those weighted keywords. Attendees can filter expert level security talks but novice level space lectures.

**Comment by klyonrad** [comment]
So @erdgeist started this in a fork `classifiers` at https://github.com/erdgeist/frab/tree/classifiers and I became motivated to finish this up :)

First draft: https://gist.github.com/klyonrad/60aaa46c1f0bf5bbf330e20fe6a1b449

Slider will be done with http://seiyria.com/bootstrap-slider/

Is the idea with five (or any number of) stars / levels still the goal? Because then I do not understand why you chose the float type for the value in `:event_classifiers`. While chatting you mentioned percent values. And that got me thinking about validations to make sure that all categories add up to 100 % etc... ;)

## some detailed questions about the UX:

* should a (new) event necessarily have a category?
* any ideas about customizing the slider-handle? 
* should there be a maximum of categories?
* should there be a default value or would you like to *force* the user of *chosing* a value?
* what about explanations for the levels - where would they go?

To the maintainers: would you want to have the feature also included in the add_fake_data rake task?

**Comment by erdgeist** [comment]
No, rating stars do not really convey the information what we want to collect. I just happened to find "raty" already being used and wrongly assumed that I could reuse functionality.

We would not need validation of the percentage sums, because they are meant per classifier. I.e. a lecture can be 80 % security on a 0-100 % and still be 70 % hardware. Also things like prior audience knowledge and things like how advanced the topic is (beginner's level up to expert) are an orthogonal property.

> should a (new) event necessarily have a category?

No, if a submitter choses not to use any of the sliders, no EventClassifier should be added to the Event

> any ideas about customizing the slider-handle?

The default looked well enough to me. I also like the whole block not to use much more Y-space as to not make the submission interface too discouraging.

> should there be a maximum of categories?

If a Conference's admin things, 50 classifiers are necessary, I don't see the need to stop them by adding arbitrary limits. It's just that the interface gets a little clunky.

> should there be a default value or would you like to force the user of chosing a value?

The default value is "off", i.e. no EventClassifier. If there would be a  checkbox that automatically gets ticked once the slider is dragged, that would be great, so you could un-check the box to denote that the EventClassifier needs to go.

> what about explanations for the levels - where would they go?

Wherever it takes the least room. Maybe add a (i) button with tooltip info on the?

> Personally I would drop that. Sounds like the computers can only err with this and human work will be needed anyway

Understood and I agree.
