### ISSUE TITLE
UX: Entering a proposal is confusing for a lot of newbies

### ISSUE THREAD

**Issue by wvholst** [frab/frab#312]
We (SHA2017 ORGA) are getting feedback that there are sufficient usability issues that people fail to put in a proposal. And to be fair, the workflow is rather counterintuitive. Most people would expect to create an event and then fill in the personal details afterwards, not the other way around.

**Comment by zonque** [comment]
Why? Creating an account, adding your personal information and then start using that account is a common pattern I figure.

**Comment by wvholst** [comment]
It clearly is not, given the existence of the complaints.

**Comment by ScottyTM** [comment]
We had zero complaints this year and in the past years about this.

**Comment by manno** [comment]
If I understand correctly this is about CfP sign up and entering a proposal. Specifically you say it would be better to enter the proposal first, the bio of the speaker afterwards.

I'm not sure if it makes any difference honestly. Sadly this cannot easily be changed, so we can't test it. The idea is to fill out your profile after sign up and then enter all the talks you want to give.
I think this is a common approach, sign up to create the user, fill out profile, create content.

I will close this feature request, because we cannot change the order of these three forms with the existing models. Maybe we could merge the user and person model, but that's a big refactor.

We could just put all three forms in a single one. I've seen the one big form approach somewhere else and I didn't like it, though.

With the latest changes a new main page has been introduced, listing all  the active conferences in a frab installation. It should help speakers who are not following the direct link to the conference specific CfP sign up page and make frab less dependent on URLs.
