### ISSUE TITLE
Generate event tokens to allow other speakers to join an event

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#358]
Currently submitting an event as a team is tedious. Submitters add a "Submission Note" that verbally informs the orga about a second or third presenter. Often those presenters don't even have an account, yet.

My proposal is to generate ( one token per event | or one for each new speaker on demand ) to pass around that allows – when presented via an extra field in the "new event" view – to be added to the event. Probably it's easier to just pass an "add me to the event"-URL in CfP scope around; as this will only work with users that have logged in (i.e. that have an account) the login mechanism will ensure that only existing users can be added.

As usual, if this is appreciated, I would implement it.

**Comment by manno** [comment]
I like it. 
One token per event should be suffcient. Maybe have add a 'join another event' button to the CFP interface. 

Using a direct URL could be done additionally, with the same token. I feel like people often have problems copying long URLs. The 'confirm talk' mail has an URL like that, which bypasses login. 

But either way, form or URL, I'm happy to have this feature. The current state is, as you said, very tedious.

Sadly we can't bypass login here, since we need to know who will be joining that talk.

**Comment by erdgeist** [comment]
I think, everything I wanted to have is now in there in #359. After review this can be merged.

**Comment by manno** [comment]
Merged in 0f3d646d2df94ba8bc56ced9cc33b3959278b9f6
