### ISSUE TITLE
Person Unavailable

### ISSUE THREAD

**Issue by gusgustavo** [frab/frab#419]
Hi, my event have activities from: 19:00 to 19:00 next day. 

So, I break it in two days:

Day 1: 19:00 - 23:55
Day 2: 00:00 - 19:00
Slot: 5 minutes (default activity 50 minutes).

I can't confirm activities from 23:55 to 00:50, because the person can't mark it's available.

**Comment by gusgustavo** [comment]
>Couldn't you use one 'day' from 19:00 to 19:00?
No, because It has too many tracks and it would be too long (~100 events). I tried this last year and with only one day, people got confused.

>What do you mean by "can't mark", is the interface broken, or is it just not working because 23:55 to 00:00 isn't part of any day?
I can't make these events to appear in the public schedule grid, because the person is unavailable.

**Comment by manno** [comment]
I looked at the submitters availability form, I guess your issue is this:

* the sliders only move in 15 minute intervals
* conferences days can't end and start on the same minute (day1: 19-00:00, day2: 00:00-19)
* you have to make the first day 'shorter', i.e. 23:55 or 23:59
* now the submitters slider can't be pulled to the end time, just to 23:45
* the submitted talk has so many 5 minute slots that it goes beyond 23:45 and thus cannot be scheduled, because the speaker can't be available for the whole time.

**Comment by gusgustavo** [comment]
Hi, i changed the file like your commit, but didn't work. Any workaround to fix this at least temporary? My conference is happening this friday.

**Comment by manno** [comment]
Did you restart the Rails server after changing the file?

**Comment by gusgustavo** [comment]
Yes, I did. But the person continues to be unavailable. I tried to update the "Availibility", but didn't changed anything.

**Comment by manno** [comment]
inactivity
