### ISSUE TITLE
Visiting pages for changing account details is impossible unless you participate in a conference

### ISSUE THREAD

**Issue by wasamasa** [frab/frab#420]
I tried changing the password for my account on the FrOSCon Frab recently.  After logging in, I clicked Account -> Settings, but that gave me a 404 as it tried visiting https://frab.froscon.de/en/cfp/user/edit.xxx.  However, joining the (yet to be announced) upcoming conference allowed me to change the user details successfully, with the new URL being https://frab.froscon.de/en/froscon2018/cfp/user/edit.xxx.

This doesn't make much sense to me.  A user account isn't linked to a conference.  Credentials established for a previous conference clearly work after the conference is over.  Furthermore, in case I'm wrong, this could be signaled, like by hiding the links requiring an activated conference.

**Comment by manno** [comment]
Well yes, previously users couldn't log in without a conference. The actual login menu was the CfP page. Technically the user account isn't linked to a conference and the new overview pages make that much clearer. 

However the CfP area is still scoped (`config/routes.rb`) by conference and there is no other form.
It should work for conference crew, though. Just not for submitters. Which is a bug.

I think this went unnoticed, because it works once you have a conference in your session.

**Comment by manno** [comment]
- [ ] Submitter without conference in session/url  can edit account
