### ISSUE TITLE
auto-login fails CSRF :bug:

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#590]
This change to repost gem https://github.com/vergilet/repost/pull/6 merged 3 days ago 😞 makes repost 0.3.0 backwards incompatible with 0.2.9.

It made LDAP (and maybe also Google) auto-login fail, because it stopped providing the [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) `authenticity_token` token on the post. As a result, auto-login caused ActionController::InvalidAuthenticityToken (at least in some setups).

**Comment by vergilet** [comment]
Sorry about that.
It was desided to remove sending the `authenticity_token` by default in version 0.3.0, because some people use it to rich the external services, where auth token from their application is needless.

To send it need to add an option: `{authenticity_token: :auto}`.
@eladeyal-intel I see you already did the fix in #591. 
Good job!
