### ISSUE TITLE
omniauth 1.8.1 gem not updateable to 1.9.0

### ISSUE THREAD

**Issue by manno** [frab/frab#659]
The `omniauth-ldap` gem is depending on the old version. I don't think we're affected, but Github lists `omniauth` 1.8.1 as vulnerable to CSRF: https://github.com/advisories/GHSA-ww4x-rwq6-qpgf

@eladeyal-intel any ideas?

**Comment by eladeyal-intel** [comment]
This link has a chapter "Mitigating in Rails applications" . I already implemented 1 and 2 when incorporating omniauth.

**Comment by eladeyal-intel** [comment]
Except that I have 

```
protect_from_forgery :except => (...) :ldap
```



I don't remember why I needed that. I'll look into it

**Comment by eladeyal-intel** [comment]
I'll try to replace the gem to https://rubygems.org/gems/gitlab_omniauth-ldap (3M downloads, last updated feb 2019)

**Comment by manno** [comment]
Thanks for looking into this :)

**Comment by eladeyal-intel** [comment]
OK I can now now explain why I think `protect_from_forgery :except => (...) :ldap` is acceptable.

The way `omniauth-ldap` works, is that it will present a form for the user to key in the username and password. The submit address for this form is the callback url
https://github.com/omniauth/omniauth-ldap/blob/3242f85968f26938d9a6ce028e511e788cc54722/lib/omniauth/strategies/ldap.rb#L30

So when `Users::OmniauthCallbacksController::ldap` is called
https://github.com/frab/frab/blob/ec0ad794b1b097e404b68bc6f19e6f096b7de578/app/controllers/users/omniauth_callbacks_controller.rb#L17 , it has the parameters `username` and `password` (in plaintext).

So in order to be admitted, the attacker would need to provide the correct username and password and can log the intended user in. So there's no attack.

**Comment by eladeyal-intel** [comment]
..or we can wait for https://github.com/omniauth/omniauth-ldap/pull/86

**Comment by eladeyal-intel** [comment]
@manno ?

**Comment by eladeyal-intel** [comment]
#663 was merged - I propose to close this issue.
