### ISSUE TITLE
Add migration test to travis

### ISSUE THREAD

**Issue by manno** [frab/frab#661]
Maybe in a separate test suite with a database dump?

**Comment by eladeyal-intel** [comment]
I tried this https://github.com/eladeyal-intel/frab/commit/654583694321871243fd070ca87ea0bab53ac98a but there are too many diffs for mysql and psql for this to be useful . sqlite tests OK though, so maybe it's worth to run int on sqlite only?

See console reports here https://travis-ci.org/eladeyal-intel/frab/builds/614740014?utm_medium=notification&utm_source=github_status

I backtracked 9 migrations because the 10th one failed to revert (it was `20181230033823_add_video_url_to_events.rb`).

**Comment by eladeyal-intel** [comment]
#662 was merged - I propose to close this ticker.
